# data base config
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# flyway test mode
spring.flyway.enabled=true

# Hibernate Envers test
spring.jpa.properties.hibernate.envers.audit_table_suffix=_aud